import { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Create Medical Report
export const createReport = async (req: Request, res: Response) => {
    try {
        const { patientId, doctorId, diagnosis, confidenceScore, preventions, chatTranscript, summary } = req.body;

        const report = await prisma.report.create({
            data: {
                patientId,
                doctorId: doctorId || null, // Optional if generated by AI only
                diagnosis,
                confidenceScore: parseFloat(confidenceScore),
                precautions: preventions || [], // JSON array
                chatTranscript: chatTranscript || {}, // JSON object
                summary
            }
        });

        res.status(201).json(report);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error creating report' });
    }
};

// Get Reports for a Patient
export const getPatientReports = async (req: Request, res: Response) => {
    try {
        const { patientId } = req.params;

        const reports = await prisma.report.findMany({
            where: { patientId },
            include: {
                doctor: { select: { name: true } }
            },
            orderBy: { createdAt: 'desc' }
        });

        res.json(reports);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error fetching reports' });
    }
};

// Get Report by ID
export const getReportById = async (req: Request, res: Response) => {
    try {
        const { id } = req.params;

        const report = await prisma.report.findUnique({
            where: { id },
            include: {
                patient: { select: { name: true, email: true } },
                doctor: { select: { name: true } }
            }
        });

        if (!report) {
            return res.status(404).json({ message: 'Report not found' });
        }

        res.json(report);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error fetching report' });
    }
};
